services:
  _defaults:
    public: false
    autowire: false
    autoconfigure: false

  netzmacht.contao_workflow.action_factory.note:
    class: Netzmacht\ContaoWorkflowBundle\Workflow\Flow\Action\Note\NoteActionFactory
    tags:
      - { name: 'netzmacht.contao_workflow.action' }

  netzmacht.contao_workflow.action_form_builder.form:
    class: Netzmacht\ContaoWorkflowBundle\Workflow\Flow\Action\Form\FormActionFormBuilder
    tags:
      - { name: 'netzmacht.contao_workflow.action_form_builder' }

  netzmacht.contao_workflow.action_factory.form:
    class: Netzmacht\ContaoWorkflowBundle\Workflow\Flow\Action\Form\FormActionFactory
    tags:
      - { name: 'netzmacht.contao_workflow.action' }

  netzmacht.contao_workflow.action_form_builder.note:
    class: Netzmacht\ContaoWorkflowBundle\Workflow\Flow\Action\Note\NoteActionFormBuilder
    tags:
      - { name: 'netzmacht.contao_workflow.action_form_builder' }

  netzmacht.contao.workflow.action_factory.notification:
    class: Netzmacht\ContaoWorkflowBundle\Workflow\Flow\Action\Notification\NotificationActionFactory
    arguments:
      - '@netzmacht.contao_toolkit.repository_manager'
      - '@netzmacht.contao_workflow.property_access_manager'
      - '@translator'
    tags:
      - { name: 'netzmacht.contao_workflow.action' }

  netzmacht.contao.workflow.action_factory.update_property:
    class: Netzmacht\ContaoWorkflowBundle\Workflow\Flow\Action\UpdatePropertyAction\UpdatePropertyActionFactory
    arguments:
      - '@netzmacht.contao_workflow.property_access_manager'
    tags:
      - { name: 'netzmacht.contao_workflow.action' }

  netzmacht.contao.workflow.action_factory.update_entity:
    class: Netzmacht\ContaoWorkflowBundle\Workflow\Flow\Action\UpdateEntityAction\UpdateEntityActionFactory
    arguments:
      - '@netzmacht.contao_toolkit.dca.manager'
      - '@netzmacht.contao_workflow.property_access_manager'
    tags:
      - { name: 'netzmacht.contao_workflow.action' }

  netzmacht.contao_workflow.action_form_builder.update_entity:
    class: Netzmacht\ContaoWorkflowBundle\Workflow\Flow\Action\UpdateEntityAction\UpdateEntityActionFormBuilder
    arguments:
      - '@netzmacht.contao_workflow.property_access_manager'
    tags:
      - { name: 'netzmacht.contao_workflow.action_form_builder' }
